trigger:
- master

pool:
  name: 'AgentDonalda'

variables:
  buildConfiguration: 'Release'
  packageVersion: '1.0.$(Build.BuildId)'
  libraryProject: 'StringLibrary'  # Your library project
  starterProject: 'ShowCase'      # Your consumer project
  feedName: 'StringExtensionLibrary/newfeed'
  feedUrl: 'https://pkgs.dev.azure.com/dzhuga/StringExtensionLibrary/_packaging/newfeed/nuget/v3/index.json'

steps:
# Step 1: Install .NET 8 SDK
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    version: '8.x'
    installationPath: 'C:\sdk'

# Step 2: Create nuget.config
- powershell: |
    @"
    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <packageSources>
        <clear />
        <add key="newfeed" value="$(feedUrl)" />
      </packageSources>
    </configuration>
    "@ | Out-File -FilePath 'nuget.config' -Encoding utf8
  displayName: 'Create nuget.config'

# Step 3: Build StringLibrary (your NuGet package)
- task: DotNetCoreCLI@2
  displayName: 'Build Library'
  inputs:
    command: 'build'
    projects: '**/$(libraryProject).csproj'
    arguments: '--configuration $(buildConfiguration)'

# Step 4: Pack StringLibrary
- task: DotNetCoreCLI@2
  displayName: 'Pack Library'
  inputs:
    command: 'pack'
    packagesToPack: '**/$(libraryProject).csproj'
    configuration: '$(buildConfiguration)'
    outputDir: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'packageVersion'

# Step 5: Push to Azure Artifacts
- task: NuGetAuthenticate@1
  displayName: 'Authenticate'

- task: DotNetCoreCLI@2
  displayName: 'Push Package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(feedName)'
    arguments: '--skip-duplicate'

# Step 6: Build ShowCase (consumer app) - Optional validation
- task: DotNetCoreCLI@2
  displayName: 'Build ShowCase'
  inputs:
    command: 'build'
    projects: '**/$(starterProject).csproj'
    arguments: '--configuration $(buildConfiguration)'