trigger:
- main

pool:
  name: 'AgentDonalda'  # Self-hosted agent

variables:
  buildConfiguration: 'Release'
  nugetFeed: 'StringExtensionLibrary/newfeed'  # Format: 'ProjectName/FeedName'

steps:
# Step 1: Install .NET 8 SDK
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    version: '8.x'
    installationPath: 'C:\sdk'

# Step 2: Restore dependencies
- task: DotNetCoreCLI@2
  displayName: 'Restore dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# Step 3: Build the project
- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --verbosity normal'
    projects: '**/*.csproj'

# Step 4: Run tests (if any)
- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Step 5: Pack NuGet package
- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '**/StringExtensionLibrary.csproj'
    versioningScheme: 'byBuildNumber'
    configuration: '$(buildConfiguration)'
    outputDir: '$(Build.ArtifactStagingDirectory)'
    arguments: '--verbosity normal'

# Step 6: Authenticate with Azure Artifacts
- task: NuGetAuthenticate@1
  displayName: 'NuGet Authenticate'

# Step 7: Push to Azure Artifacts
- task: DotNetCoreCLI@2
  displayName: 'Push to Azure Artifacts'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(nugetFeed)'
    arguments: '--verbosity detailed'  # This is the correct way to set verbosity