trigger:
- main

pool:
  name: Default  # Your self-hosted agent pool
  demands:
  - agent.os -equals Windows_NT

variables:
  buildConfiguration: 'Release'
  feedName: 'donaldafeed'  # Your specific feed name
  # For organization-scoped feeds:
  feedUrl: 'https://pkgs.dev.azure.com/$(System.TeamFoundationCollectionUri)/_packaging/$(feedName)/nuget/v3/index.json'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    version: '8.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '$(feedName)'

- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Create NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '**/StringExtensionLibrary.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'
    outputDir: '$(Build.ArtifactStagingDirectory)'

# Modern authentication approach
- task: DotNetCoreCLI@2
  displayName: 'Push to donaldafeed'
  inputs:
    command: 'nuget push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    feedsToUse: 'select'
    vstsFeed: '$(feedName)'
    publishFeedCredentials: '$(System.AccessToken)'